server:
  port: 8761 # eureka server http port。Recommended to use 8761，but it is 8080 by default

eureka:
  client:
    # Normally，eureka server is also a eureka client，which is used when applying high availability eureka service.
    # When it is a standalone service，if registerWithEureka is set true，the eureka server will prompt "Cannot execute request on any known server" error
    registerWithEureka: false # 是否注册到eureka服务，默认为true，当前已为eureka server，且单点eureka，故配置为false
    fetchRegistry: false # 是否在本地缓存注册表信息，默认为true，当前为单点eureka server，不需要从其他eureka除获取注册表信息，更谈不上缓存，故配置为false
    #server:
    # 在服务器接收请求之前等待的初始时间，默认等待5min（John Carnell）
    #waitTimeInMsWhenSyncEmpty: 5 # John说开发时最好注释此配置，服务注册需要3次心跳，每次10s，也就是30s才能显示在eureka。但是为什么我这里马上就显示呢？

# 指定生效的配置
spring:
  profiles:
    active: dev
  freemarker:
    prefer-file-system-access: false


# 用三个连接符进行profile分割，根据active的profiles选择执行哪一段，上面没有profiles的表示公共执行部分
---

# 本地开发环境
spring:
  profiles: dev

security:                           # 开启服务注册认证机制
  basic:
    enabled: true                 # 是否开启认证，默认true，需开启时可省略。
  user:
    name: eureka                  # 认证时，使用的用户名
    password: eureka              # 认证时，使用的密码

eureka:
  # 详见EurekaServerConfigBean，需要注意与Client和Instance在client的jar包不同，Server是在server的jar包。
  # eureka的各项配置可见EurekaXXXConfigBean。
  server:
    # 自我保护机制，默认true。打开后，心跳失败在15分钟内低于85%(renewalPercentThreshold)的服务，也不进行剔除。
    # 关闭后，主页提示：RENEWALS ARE LESSER THAN THE THRESHOLD. THE SELF PRESERVATION MODE IS TURNED OFF.
    # THIS MAY NOT PROTECT INSTANCE EXPIRY IN CASE OF NETWORK/OTHER PROBLEMS.
    enableSelfPreservation: true # 本地调试时可fasle关闭。但生产建议打开，可防止因网络不稳定等原因导致误剔除服务。
    renewalPercentThreshold: 0.85 # 默认85%
  client:
    serviceUrl:
      # registerWithEureka关闭后，defaultZone没有配置的必要。如果打开，即使配置为本机一样报错。
      # 也就是说defaultZone任何时候都没有配置为localhost的必要。这点上John的配置更好，永超和周立包括志朋的配置有点多余。
      # 但是周立说的对，这个属性默认配置是http://localhost:8761/eureka，也就是当你没有用户名密码安全认证时，本机调试时，客户端可以不配置，
      # 但对于server来说，这个默认没有什么作用。对于client来说，也只有调试的时候有点作用。
      # 但有一点很奇怪，既然默认了8761端口，为什么eureka server的默认端口要用8080而不是8761呢？
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:${server.port}/eureka # 本配置应删除。

---

# 测试环境。profiles配置为主机名，根据主机名进行激活，需在启动脚本中--spring.profiles.active=${HOST_NAME}，
# 因为启动脚本的优先级比本文件的active优先级高。
# 多台eureka高可用环境下，每台eureka的defaultZone配置都不一样，因为不能把自己也配置上，因为为了保证每台eureka的代码配置一致方便发布，
# 需要采取yml的---分隔，然后通过主机名启动这种模式进行。
spring:
  profiles: hifu-test1

security:
  user:
    name: eureka
    password: eureka

eureka:
  instance:
    hostname: hifu-test1
  server:
    # eureka server刷新readCacheMap的时间，注意，client读取的是readCacheMap，这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上
    # 默认30秒，eclipse提示默认0应该是错误的，源代码中responseCacheUpdateIntervalMs = 30 * 1000。
    response-cache-update-interval-ms: 3000 # 网上很多专家的博客错误写成responseCacheUpdateInvervalMs，请注意。这里配置为3秒。
    # eureka server缓存readWriteCacheMap失效时间，这个只有在这个时间过去后缓存才会失效，失效前不会更新，
    # 过期后从registry重新读取注册服务信息，registry是一个ConcurrentHashMap。
    # 由于启用了evict其实就用不太上改这个配置了，默认180s
    responseCacheAutoExpirationInSeconds: 180
    # 启用主动失效，并且每次主动失效检测间隔为3s。源码evictionIntervalTimerInMs = 60 * 1000，默认一分钟。
    # 需要注意的是该配置会打印INFO日志，增加info日志量，修改后从每60秒打印一次变成3秒打印一次。
    evictionIntervalTimerInMs: 3000 # 注意不要写成EvictionIntervalTimerInMs，yml大小写敏感。
  client:
    serviceUrl:
      # 配置其他eureka的地址，如果多台则逗号分隔。
      defaultZone: http://${security.user.name}:${security.user.password}@10.13.22.19:${server.port}/eureka
    healthcheck:
      enabled: true
    registerWithEureka: true # eureka的高可用，需要互相注册，配置为true，覆盖本文件最上面的默认配置false。
    fetchRegistry: false # eureka之间如果网络不稳定，客户端一般也会缓存了注册列表，因此eureka服务可以不缓存，我觉得更能确保eureka之间的一致。

---
spring:
  profiles: hifu-test2

security:
  user:
    name: eureka
    password: eureka

eureka:
  instance:
    hostname: hifu-test2
  server:
    responseCacheUpdateIntervalMs: 3000
    responseCacheAutoExpirationInSeconds: 180
    evictionIntervalTimerInMs: 3000
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@10.13.22.18:${server.port}/eureka
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: false